Week 14 - Nathalie Rautell
Technigo/project-redux-quiz-old pull request #3
Opened 2020-05-10 21:36 UTC by rautellin

Managed to do this assignment by myself, which im kinda proud of. It was real fun to do as well.

2020-06-15 14:29 UTC, HIPPIEKICK requested changes
Impressive! So many nice features and extras 🥳  Unfortunately, you missed one of the requirements:
- When the user selects an answer, it should show if they were correct or not.

Fix this and it's approved!

2020-06-15 14:29 UTC, HIPPIEKICK commented on src/components/TimeIsUp.js
> +}
😅

2020-07-01 18:56 UTC, rautellin commented
The missing feature is now added. 👍

2020-07-02 12:40 UTC, HIPPIEKICK approved these changes

2020-11-16 08:39 UTC, closed without merging